### ISSUE TITLE
Allow for emacs style keybindings in insert mode (Ctrl-a & Ctrl-e)

### ISSUE THREAD

**Issue by rkabrick** [zap-zsh/vim#3]
Howdy! 

I'd love if there was an option in this (or some snippet I can add to my config) to enable support for `ctrl-e` & `ctrl-a` keybindings. I know `Esc 0` would work but it would be nice to be able to do this. Thanks for the awesome work

**Comment by chrishrbAtJambit** [comment]
Hi @rkabrick ,
i created a PR for this issue because I wanted the same feature for myself 😄 If you don‘t want to wait for the PR you can also add the lines to your zshrc:
```zsh
bindkey -M viins '^A' beginning-of-line 
bindkey -M viins '^E' end-of-line 
```
