### ISSUE TITLE
cannot remap from viins mode

### ISSUE THREAD

**Issue by gennaro-tedesco** [zap-zsh/vim#6]
Thank you for the great work on `zap`! 

I have replaced `ohmyzsh` vi-mode plugin with the current one, however I have noticed that with this one I cannot seem to define mappings in insert mode along the lines of
```sh
bindkey -M viins '<some mappings>' vi-cmd-mode
```
namely such mappings, although defined, seem to have no effect.

The use case I have is to re-define a mapping to escape back into normal mode (I presume this is quite a common use case for many who do not want to reach out to `Esc` far away in the upper left corner). Would a re-mapping like the above work for you (and perhaps I have some other settings that conflict, though I do not believe so, I have minimally reproduced it) or how do you suggest to go around it, otherwise?

P. S. Since the above is quite a common use case, why not exposing a variable to the user who could then set their favourite escape sequence? Something along the lines of `VI_MODE_ESC_INSERT='...'`?

**Comment by gennaro-tedesco** [comment]
It seems that [this line](https://github.com/zap-zsh/vim/blob/5f28bd7579c47fa374c32b3a9ff20bbce0b200b9/vim.plugin.zsh#L3) is the culprit. I have opened a PR to expose an env variable for the user to set a custom escape sequence, furthermore amending the timeout.

**Comment by raul-bns** [comment]
Hi,
Maybe i didn't follow well.
There is a way to change Esc to another key combination to enter in normal mode ??
Thanks

**Comment by gennaro-tedesco** [comment]
Yes, see the linked PR.

**Comment by raul-bns** [comment]
Cool, thanks a lot. That works

**Comment by mamaraddio** [comment]
Merged PR #7
